anhui:
  xiaoxian:
    shiyan:
      name: 悟空

server:
  port: 8120

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 不想使用 Nacos 作为您的服务注册与发现,设置为false
        enabled: true
      username: nacos
      password: nacos


